CREATE TABLE [dbo].[ProfileInformation] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Sub] uniqueidentifier  NULL,
    [FirstName] varchar(50)  NULL,
    [LastName] varchar(50)  NULL,
    [EmailAddress] varchar(50)  NULL,
    [State] varchar(10)  NULL,
    [Postcode] nvarchar(50)  NULL,
	 [AddressLine1] varchar(500)  NULL,
	  [AddressLine2] varchar(500)  NULL,
	   [City] varchar(500)  NULL,
	   [MobileNumber] varchar(50)  NULL,
	   [PhoneNumber] varchar(50)  NULL, 
    [IsActive] BIT NULL, 
    [Organization] VARCHAR(500) NULL, 
    [ContactPerson] VARCHAR(500) NULL, 
    [PhoneNumberOfContactPerson] VARCHAR(50) NULL, 
    [Address] VARCHAR(500) NULL, 
    [Address2] VARCHAR(500) NULL, 
    [Website] VARCHAR(500) NULL, 
    [NotForProfit] BIT NULL,
);
