CREATE TABLE [dbo].[RegionsLGA]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY ,
	[Region] NVARCHAR(1000) NOT NULL, 
	[LGA] NVARCHAR(1000) NOT NULL, 
	[Location1] NVARCHAR(1000) NULL, 
	[Location2] NVARCHAR(1000) NULL, 
	[Location3] NVARCHAR(1000) NULL
)
