CREATE TABLE [dbo].[RegionLGAAssessor]
(
	[AssessorId] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[RegionLGAId] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL, 
	CONSTRAINT [PK_RegionLGAAssessor] PRIMARY KEY ([AssessorId], [RegionLGAId]),
	CONSTRAINT [FK_RegionLGAAssessor_RegionsLGA] FOREIGN KEY (RegionLGAId) REFERENCES RegionsLGA(Id)  
)
