CREATE TABLE [dbo].[DocLibDocumentNotes]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY ,
	[NoteAddedDate] DATETIME NULL,
	[Note] NVARCHAR(1000) NULL,
	[DocumentID] UNIQUEIDENTIFIER  NOT NULL, 	 
	CONSTRAINT [FK_DocLibDocumentNotes_Document] FOREIGN KEY (DocumentID) REFERENCES Document(DocumentID)
)